feat:Styling app
taher-software/Bookstore pull request #4
Opened 2021-12-09 21:12 UTC by Taher-web-dev

In this branch, I've used the book store design in zeplin to style my application. So please review how much my application match the zeplin application and send me your feedback before to move forward the next step.
Looking forward your review.
Best,

2021-12-09 23:35 UTC, ArthurGC requested changes
# Required Changes ♻️ :warning: 
Hi  @Taher-web-dev 

Amazing job!
There are some issues that you still need to work on to go to the next project but you are almost there! 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :
You used proper GitHub Flow :heavy_check_mark:
Your linter checks are all passing :heavy_check_mark:
Your PR messages are descriptive :heavy_check_mark:
Your commit messages are meaningful :heavy_check_mark:

## Aspects to improve ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-09 23:35 UTC, ArthurGC commented on src/components/Books/BooksList.js
>            </li>
- [ ] As the requirements show: 😉 

![design-requirements](https://user-images.githubusercontent.com/79876959/145491491-f7d9c9a4-c4aa-4efb-8d93-77913e556283.PNG)

It is necessary to implement this part too for each card. (You don't need to add any functionality for those.)

![design-requirements-2](https://user-images.githubusercontent.com/79876959/145491681-b6642b3b-606b-4d42-8d2d-0525020ddee0.PNG)

2021-12-09 23:35 UTC, ArthurGC commented on src/components/Books/Form.js
> +          <option disabled selected hidden>Category</option>
- [ ] You want to consider fixing the `width` property of your  `ADD NEW BOOK` text to match the template. ♻️ 

![design-requirements-3](https://user-images.githubusercontent.com/79876959/145492033-558d7d26-fe18-4819-bce0-14e7378375e3.PNG)

2021-12-10 16:20 UTC, Emmyn5600 approved these changes
STATUS: APPROVED :+1: 

Hello, @Taher-web-dev  👋🏾 👋🏾 congratulations on implementing all the changes requested by the previous reviewer as well as the project requirements.

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

2021-12-10 16:59 UTC, merged